"""add_provider_usage_logs

Revision ID: c91bb50c5484
Revises: f9a0b1c2d3e4
Create Date: 2026-04-03 02:27:54.863590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c91bb50c5484'
down_revision: Union[str, None] = 'f9a0b1c2d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('records_returned', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=True),
    sa.Column('credits_estimated', sa.Integer(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_usage_logs_client_id', 'provider_usage_logs', ['client_id'], unique=False)
    op.create_index('ix_provider_usage_logs_client_provider', 'provider_usage_logs', ['client_id', 'provider'], unique=False)
    op.create_index('ix_provider_usage_logs_created_at', 'provider_usage_logs', ['created_at'], unique=False)
    op.create_index('ix_provider_usage_logs_provider', 'provider_usage_logs', ['provider'], unique=False)
    op.drop_index('ix_companies_enrichment_data_gin', table_name='companies', postgresql_using='gin')
    op.drop_index('ix_leads_enrichment_data_gin', table_name='leads', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_leads_enrichment_data_gin', 'leads', ['enrichment_data'], unique=False, postgresql_using='gin')
    op.create_index('ix_companies_enrichment_data_gin', 'companies', ['enrichment_data'], unique=False, postgresql_using='gin')
    op.drop_index('ix_provider_usage_logs_provider', table_name='provider_usage_logs')
    op.drop_index('ix_provider_usage_logs_created_at', table_name='provider_usage_logs')
    op.drop_index('ix_provider_usage_logs_client_provider', table_name='provider_usage_logs')
    op.drop_index('ix_provider_usage_logs_client_id', table_name='provider_usage_logs')
    op.drop_table('provider_usage_logs')
    # ### end Alembic commands ###
